eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8099
spring:
  application:
    name: service-hi
  mvc:
    static-path-pattern:/static/**  
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iyue_info?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb